### ISSUE TITLE
Only able to record one code in ir_codes.json..?

### ISSUE THREAD

**Issue by CodeSpotter** [crleblanc/hackPump#3]
First: Kudos for an excellent project. 

I am well on my way to getting this working (I think), but when trying to record the IR codes from my existing remote something fails. For some reason the ir_codes.json file only ends up with one code / line item. This is typically the last one recorded before I hit enter to exit  "record_codes.py". Any idea of what may be causing this? 

I may get around this by recording the codes individually and merging these into one file when done. Could you please indicate what the structure of the "ir_codes.json" file should look like when complete, specifically: What symbol is used to separate the individual codes (and this is were I reveal my inexperience in reading and understanding python code snippets...)?

I realize this is a project you completed a long time ago, so you may have abandoned this - but if you take time to respond I would be very grateful. Thanks!

**Comment by crleblanc** [comment]
Hi CodeSpotter,

Unfortunately I haven't had long term success with the IR toy.  There is a bug report for the underlying "pyirtoy" library that describes the problem in more detail: https://github.com/crleblanc/PyIrToy/issues/2.  In summary the device stops working when there is a buffer underflow (the computer can't supply data quick enough).  I've noticed this is especially bad on the Raspberry Pi but may never happen on a desktop/laptop.

I wonder if your recording problems are related to this?  The .json file is standard JSON (javascript object notation), and is a dictionary where the key:value pairs are string->a list of ints.  Here's a cooked up example:

{"24": [0, 159, 0, 81, 0, 21, 0, 255, 255], "26": [0, 160, 0, 80,255, 255]}

As an aside there is now a commercial product that sounds like it could replace this project, called the Sensibo.  I'm hopeful this would be a simple plug and play operation and would be more reliable than the IR toy.  It would be great to get the IR toy working, but it seems like development of the firmware has stopped, so I don't expect it's bugs to be fixed.

I'll put a note in the readme for this project and the pyirtoy library mentioning it's lack of stability.

**Comment by CodeSpotter** [comment]
Thanks for your response. I agree it looks like a firmware issue and the problems described in the "pyirtoy" library appear very similar to what I am experiencing. I'll close this issue based on your response.
